- name: Deploy trueodysseys
  gather_facts: false
  hosts: all
  vars:
    AWS_ECR_REGISTRY: 654654475781.dkr.ecr.eu-west-1.amazonaws.com
    AWS_REGION: eu-west-1
    APP_DIR: /home/ubuntu/trueodysseys
    APP: trueodysseys
    IMAGE_TAG: '{{ image_tag }}'
  tasks:
    - name: Generate docker credentials
      ansible.builtin.shell: |
        aws ecr get-login-password --region {{ AWS_REGION }} | docker login --username AWS --password-stdin {{ AWS_ECR_REGISTRY }}

    - name: Make app dir
      ansible.builtin.file:
        path: '{{ APP_DIR }}'
        state: directory
        mode: '0755'

    - name: Copy stack file
      ansible.builtin.copy:
        src: stack.yml
        dest: '{{ APP_DIR }}'
        mode: '0755'
        force: yes

    - name: Deploy stack
      ansible.builtin.shell: |
        export IMAGE_TAG={{ IMAGE_TAG }}
        docker network create -d overlay --attachable public
        docker stack deploy --with-registry-auth -c {{ APP_DIR }}/stack.yml {{ APP }}
      register: result

    - name: Display output
      debug:
        var: result.stdout_lines
